[debug] [2018-11-10T21:27:16.325Z] ----------------------------------------------------------------------
[debug] [2018-11-10T21:27:16.327Z] Command:       /usr/bin/node /usr/bin/firebase serve
[debug] [2018-11-10T21:27:16.327Z] CLI Version:   6.0.1
[debug] [2018-11-10T21:27:16.327Z] Platform:      linux
[debug] [2018-11-10T21:27:16.327Z] Node Version:  v10.12.0
[debug] [2018-11-10T21:27:16.328Z] Time:          Sat Nov 10 2018 22:27:16 GMT+0100 (Central European Standard Time)
[debug] [2018-11-10T21:27:16.328Z] ----------------------------------------------------------------------
[debug] 
[debug] [2018-11-10T21:27:16.338Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2018-11-10T21:27:16.338Z] > authorizing via signed-in user
[debug] [2018-11-10T21:27:16.339Z] [iam] checking project appointments-pwa for permissions ["firebase.projects.get"]
[debug] [2018-11-10T21:27:16.340Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2018-11-10T21:27:16.340Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2018-11-10T21:27:16.577Z] <<< HTTP RESPONSE 200
[debug] [2018-11-10T21:27:16.583Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/appointments-pwa:testIamPermissions  

[debug] [2018-11-10T21:27:17.641Z] <<< HTTP RESPONSE 200
[debug] [2018-11-10T21:27:17.645Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/appointments-pwa  
 
[debug] [2018-11-10T21:27:18.665Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/home/kaindl/Documents/appointments-pwa'...
[info] 
[debug] [2018-11-10T21:27:19.195Z] Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/logs'
    at Object.mkdirSync (fs.js:750:3)
    at Object.assertLogsPath (/usr/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:65:10)
    at new Controller (/usr/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:77:32)
    at FunctionsEmulator.start (/usr/lib/node_modules/firebase-tools/lib/functionsEmulator.js:102:23)
    at Object.start (/usr/lib/node_modules/firebase-tools/lib/serve/functions.js:7:33)
    at /usr/lib/node_modules/firebase-tools/lib/serve/index.js:18:23
    at arrayMap (/usr/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at Function.map (/usr/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9556:14)
    at _serve (/usr/lib/node_modules/firebase-tools/lib/serve/index.js:16:26)
    at Command._action (/usr/lib/node_modules/firebase-tools/lib/commands/serve.js:58:12)
[error] 
[error] Error: An unexpected error has occurred.
